// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwIqf9EibFaSAsDShVTJJLR3fph4tkaiw',
    appId: '1:749200305578:web:e6e805b7f4ed0128dbcfd3',
    messagingSenderId: '749200305578',
    projectId: 'socialapp-6a8e1',
    authDomain: 'socialapp-6a8e1.firebaseapp.com',
    storageBucket: 'socialapp-6a8e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwbrQ4AABqHngOgZiD05i8ngqygM-5_yc',
    appId: '1:749200305578:android:32a87a7f045f835edbcfd3',
    messagingSenderId: '749200305578',
    projectId: 'socialapp-6a8e1',
    storageBucket: 'socialapp-6a8e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqjVjaQvuursms1tE31xEKnNFOndG2i3o',
    appId: '1:749200305578:ios:9b6adb77403566f6dbcfd3',
    messagingSenderId: '749200305578',
    projectId: 'socialapp-6a8e1',
    storageBucket: 'socialapp-6a8e1.appspot.com',
    iosClientId: '749200305578-gr5vcjstit8s5rv811of5kfm7k46uar2.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqjVjaQvuursms1tE31xEKnNFOndG2i3o',
    appId: '1:749200305578:ios:44ef3baabc334091dbcfd3',
    messagingSenderId: '749200305578',
    projectId: 'socialapp-6a8e1',
    storageBucket: 'socialapp-6a8e1.appspot.com',
    iosClientId: '749200305578-gj54unlnrjkq5ehso8scm901ta1ltcrb.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
